loopback_ip: 10.199.18.21
management_ip: 172.18.30.21

def_gateway: 172.16.2.1

uplinks:
  - desc: Naar b1-distsw01
    my_port: Ethernet0/0
    my_ip: 172.18.2.2/30
    remote_port: Ethernet2/0
    remote_ip: 172.18.2.1/30
