loopback_ip: 10.199.10.11
management_ip: 172.10.30.1

def_gateway: 10.0.11.1

uplinks:
  - desc: Naar WAN1
    my_port: Ethernet0/0
    my_ip: 1.1.1.1/24
    remote_port: WAN 1 Provider
    remote_ip: PE
  - desc: Naar hq-distsw01
    my_port: Ethernet0/1
    my_ip: 10.0.11.2/30
    remote_port: Ethernet0/0
    remote_ip: 10.0.11.1/30
